//! Local identity: the endpoint UUID, `/etc/smb.conf` parameters and the
//! host name.  All of it is pure: the daemon reads the files and hands the
//! bytes here.

/// Canonical UUID text length, `UUIDLEN - 1` in the vendor (`wsd.c:69`).
pub const UUID_LEN: usize = 36;
/// Longest value accepted from `/etc/smb.conf`; the vendor used a 256-byte
/// value buffer (`wsdd2.c:626`).
pub const MAX_SMB_VALUE: usize = 255;

/// Parses the contents of `/etc/machine-id` or
/// `/proc/sys/kernel/random/boot_id` into a canonical endpoint UUID.
///
/// `wsd.c:126-163` accepted any 36-character run of `-`, digits and
/// lower-case hex, then re-derived the dashes; this requires the canonical
/// `8-4-4-4-12` shape outright, which every writer of either file produces.
///
/// Returns `None` when the file holds anything else, which disables
/// WS-Discovery exactly as `wsd_init` failing did (`wsd.c:1004-1012`).
#[must_use]
pub fn parse_endpoint_uuid(contents: &[u8]) -> Option<String> {
    let text = core::str::from_utf8(contents).ok()?;
    let candidate = text.trim();
    if candidate.len() != UUID_LEN {
        return None;
    }
    let mut groups = candidate.split('-');
    for expected in [8_usize, 4, 4, 4, 12] {
        let group = groups.next()?;
        if group.len() != expected
            || !group
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return None;
        }
    }
    if groups.next().is_some() {
        return None;
    }
    Some(candidate.to_owned())
}

/// Formats sixteen random bytes as a canonical lower-case UUID.
///
/// The vendor built its sequence identifier from `mrand48()`
/// (`wsd.c:108-124`) seeded with the endpoint UUID and the wall clock
/// (`wsd.c:89-106`), which makes it predictable.  This one is fed from
/// `/dev/urandom`.
#[must_use]
pub fn format_uuid(bytes: [u8; 16]) -> String {
    let mut out = String::with_capacity(UUID_LEN);
    for (index, byte) in bytes.iter().enumerate() {
        if matches!(index, 4 | 6 | 8 | 10) {
            out.push('-');
        }
        out.push(hex_digit(byte >> 4));
        out.push(hex_digit(byte & 0x0f));
    }
    out
}

fn hex_digit(value: u8) -> char {
    match value {
        0..=9 => char::from(b'0'.saturating_add(value)),
        _ => char::from(b'a'.saturating_add(value.saturating_sub(10))),
    }
}

/// Reads one parameter out of an `smb.conf`.
///
/// `wsdd2.c:621-702` did this with two hand-rolled copy loops over fixed
/// buffers.  The grammar accepted here is the same: the first line whose
/// text before `=` trims to `name`, with the text after `=` trimmed as the
/// value.  Section headers, comments and continuations are not interpreted,
/// because the vendor did not interpret them either and the file this reads
/// is generated by `rc`.
#[must_use]
pub fn smb_parameter(contents: &[u8], name: &str) -> Option<String> {
    for line in contents.split(|byte| *byte == b'\n') {
        let Ok(line) = core::str::from_utf8(line) else {
            continue;
        };
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        if !key.trim().eq_ignore_ascii_case(name) {
            continue;
        }
        let value = value.trim();
        if value.is_empty() || value.len() > MAX_SMB_VALUE {
            return None;
        }
        if !value
            .bytes()
            .all(|byte| byte.is_ascii_graphic() || byte == b' ')
        {
            return None;
        }
        return Some(value.to_owned());
    }
    None
}

/// Trims a host name the way `init_sysinfo` did (`wsdd2.c:742-744`): drop
/// everything from the first dot, then require a usable label.
#[must_use]
pub fn short_hostname(raw: &str) -> Option<String> {
    let short = raw.split('.').next().unwrap_or_default().trim();
    if short.is_empty() || short.len() > MAX_SMB_VALUE {
        return None;
    }
    if !short
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    {
        return None;
    }
    Some(short.to_owned())
}
