[package]
name = "router-fuzz"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "GPL-2.0-only"
publish = false

[dependencies]
httpd-parsers = { path = "../httpd-parsers" }
infosvr = { path = "../infosvr" }
router-policy = { path = "../router-policy" }
rstats = { path = "../rstats" }
wanduck-transition = { path = "../wanduck-transition" }
