[package]
name = "router-fuzz"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "GPL-2.0-only"
publish = false

[dependencies]
clientlist = { path = "../clientlist" }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
httpd-parsers = { path = "../httpd-parsers" }
infosvr = { path = "../infosvr" }
router-policy = { path = "../router-policy" }
rstats = { path = "../rstats" }
wanduck-transition = { path = "../wanduck-transition" }
wlif-policy = { path = "../wlif-policy" }
