#!/usr/bin/env bash
# FAILED portability experiment, not a working kernel build recipe.
# Run only in a separate lab source copy; never on the firmware source tree.
set -euo pipefail
test -f Kconfig
rg -q 'config QEMU_LAB' Kconfig
for option in PRINTK BUG MULTIUSER SYSVIPC POSIX_TIMERS FUTEX EPOLL SIGNALFD TIMERFD EVENTFD \
  BINFMT_ELF BINFMT_SCRIPT COMPAT BLK_DEV_INITRD RD_GZIP DEVTMPFS DEVTMPFS_MOUNT \
  PROC_FS SYSFS TMPFS TTY SERIAL_AMBA_PL011 SERIAL_AMBA_PL011_CONSOLE \
  ARM_AMBA ARM_GIC ARM_ARCH_TIMER ARCH_VEXPRESS \
  NET UNIX PACKET INET IPV6 NETDEVICES VIRTIO VIRTIO_MMIO VIRTIO_NET TUN \
  NETFILTER NETFILTER_ADVANCED NF_CONNTRACK NF_NAT NETFILTER_XTABLES \
  NETFILTER_XT_MATCH_CONNTRACK NETFILTER_XT_TARGET_MARK IP_NF_IPTABLES IP_NF_FILTER \
  IP_NF_NAT IP6_NF_IPTABLES IP6_NF_FILTER NET_SCHED NET_SCH_NETEM \
  WIRELESS WLAN CFG80211 MAC80211 MAC80211_HWSIM CRYPTO CRYPTO_AES CRYPTO_CCM \
  DEBUG_KERNEL DEBUG_INFO; do
  scripts/config --enable "$option"
done
scripts/config --set-str LOCALVERSION '-qemu-lab' --disable LOCALVERSION_AUTO
# External initramfs is supplied by the lab runner, not embedded host paths.
scripts/config --set-str INITRAMFS_SOURCE ''
